### PR TITLE
OpenAPI spec generation with flask-openapi3

### PR DESCRIPTION
**Pull request by JamesClarke7283**
I saw you made a help page for the REST API for ContentDB.
[https://content.minetest.net/help/api/](https://content.minetest.net/help/api/)
Did you know there is a more formal way to document REST APIs?

[The OpenAPI spec.](https://swagger.io/specification/v2/)

I am mostly making this PR so i can easily make a custom ChatGPT that interfaces with minetests ContentDB.
They take a OpenAPI spec as input for the actions, so i though i might as well kill two birds with one stone.
Use this so i can integrate contentDB with chatGPT and also help you document your project as well.

Here is the list of endpoints to complete:

- [ ] /api/cdb_schema/
- [ ] /api/collections/
- [ ] /api/collections/<author>/<name>/
- [ ] /api/content_warnings/
- [ ] /api/delete-token/
- [ ] /api/dependencies/
- [ ] /api/homepage/
- [ ] /api/hypertext/
- [ ] /api/licenses/
- [ ] /api/markdown/
- [ ] /api/minetest_versions/
- [ ] /api/packages/
- [ ] /api/packages/<author>/<name>/
- [ ] /api/packages/<author>/<name>/dependencies/
- [ ] /api/packages/<author>/<name>/hypertext/
- [ ] /api/packages/<author>/<name>/releases/
- [ ] /api/packages/<author>/<name>/releases/<int:id>/
- [ ] /api/packages/<author>/<name>/releases/new/
- [ ] /api/packages/<author>/<name>/reviews/
- [ ] /api/packages/<author>/<name>/screenshots/
- [ ] /api/packages/<author>/<name>/screenshots/cover-image/
- [ ] /api/packages/<author>/<name>/screenshots/<int:id>/
- [ ] /api/packages/<author>/<name>/screenshots/new/
- [ ] /api/packages/<author>/<name>/screenshots/order/
- [ ] /api/packages/<author>/<name>/stats/
- [ ] /api/package_stats/
- [ ] /api/releases/
- [ ] /api/reviews/
- [ ] /api/scores/
- [ ] /api/spec/
- [ ] /api/tags/
- [ ] /api/topic_discard/
- [ ] /api/topics/
- [ ] /api/updates/
- [ ] /api/users/<username>/
- [ ] /api/users/<username>/stats/
- [ ] /api/welcome/v1/
- [ ] /api/whoami/

This PR adds the following dependencies:
- [Flask OpenAPI 3](https://pypi.org/project/flask-openapi3)
- [Pydantic SQLalchemy](https://pypi.org/project/pydantic-sqlalchemy/)

### CODE REVIEW

**Comment by rubenwardy** [comment]
Nice! Yeah, I know about OpenAPI now - just didn't in 2018. Thanks for working on this

**Comment by JamesClarke7283** [comment]
> Nice! Yeah, I know about OpenAPI now - just didn't in 2018. Thanks for working on this

The good thing about `flask-openapi3` is if the datatypes change, it will update itself, apart from the human text descriptions for what the parameters do. but the actual definitions are autogenerated.

Now ive just got to figure out how to use the SqlAlchemy models as Pydantic models with `pydantic-sqlalchemy`

**Comment by JamesClarke7283** [comment]
> Nice! Yeah, I know about OpenAPI now - just didn't in 2018. Thanks for working on this

Could you help me a tad with this PR a tad?
whenever i add this to the `app/blueprints/__init__.py` file, it gives an error.
```python
from app import app as flask_app
flask_app.register_api(bp)
```
Error:
```plaintext
worker-1    |   File "/home/cdb/app/__init__.py", line 101, in <module>
worker-1    |     create_blueprints(app)
worker-1    |   File "/home/cdb/app/blueprints/__init__.py", line 28, in create_blueprints
worker-1    |     app.register_blueprint(module.bp)
worker-1    |   File "/usr/local/lib/python3.10/site-packages/flask/scaffold.py", line 50, in wrapper_func
worker-1    |     return f(self, *args, **kwargs)
worker-1    |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1299, in register_blueprint

worker-1    |     blueprint.register(self, options)
worker-1    |   File "/usr/local/lib/python3.10/site-packages/flask/blueprints.py", line 384, in register
worker-1    |     raise ValueError(
worker-1    | ValueError: Couldn't import 'app.tasks.celery': The name 'api' is already registered for this blueprint. Use 'name=' to provide a unique name.
worker-1    |
app-1       | Traceback (most recent call last):
app-1       |   File "/usr/local/bin/flask", line 8, in <module>
app-1       |     sys.exit(main())
app-1       |   File "/usr/local/lib/python3.10/site-packages/flask/cli.py", line 1050, in main
app-1       |     cli.main()
app-1       |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
app-1       |     rv = self.invoke(ctx)
app-1       |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
app-1       |     return _process_result(sub_ctx.command.invoke(sub_ctx))
app-1       |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
app-1       |     return ctx.invoke(self.callback, **ctx.params)
app-1       |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
app-1       |     return __callback(*args, **kwargs)
app-1       |   File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 84, in new_func
app-1       |     return ctx.invoke(f, obj, *args, **kwargs)
app-1       |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
app-1       |     return __callback(*args, **kwargs)
app-1       |   File "/usr/local/lib/python3.10/site-packages/flask/cli.py", line 911, in run_command
app-1       |     raise e from None
app-1       |   File "/usr/local/lib/python3.10/site-packages/flask/cli.py", line 897, in run_command
app-1       |     app = info.load_app()
app-1       |   File "/usr/local/lib/python3.10/site-packages/flask/cli.py", line 308, in load_app
app-1       |     app = locate_app(import_name, name)
app-1       |   File "/usr/local/lib/python3.10/site-packages/flask/cli.py", line 218, in locate_app
app-1       |     __import__(module_name)
app-1       |   File "/home/cdb/app/__init__.py", line 101, in <module>
app-1       |     create_blueprints(app)
app-1       |   File "/home/cdb/app/blueprints/__init__.py", line 28, in create_blueprints
app-1       |     app.register_blueprint(module.bp)
app-1       |   File "/usr/local/lib/python3.10/site-packages/flask/scaffold.py", line 50, in wrapper_func
app-1       |     return f(self, *args, **kwargs)
app-1       |   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1299, in register_blueprint
app-1       |     blueprint.register(self, options)
app-1       |   File "/usr/local/lib/python3.10/site-packages/flask/blueprints.py", line 384, in register
app-1       |     raise ValueError(
app-1       | ValueError: The name 'api' is already registered for this blueprint. Use 'name=' to provide a unique name.
```

**Comment by rubenwardy** [comment]
Do you still need help with this? I thought you resolved it given your commits afterwards

**Pull request closed without merging**
