### PR TITLE
Improve placeholder.png image

### PR DESCRIPTION
**Pull request by xenonca**
Old:
placeholder_old
New:
placeholder

### CODE REVIEW

**Comment by rubenwardy** [comment]
What does a flat subtle version of this look like? It would work better with the rest of the site imo

**Comment by xenonca** [comment]
I've come up with 3 options for a flat version of this one:
image
A simple flat one (top left), a contrast flat (middle left) and a silhouette flat (bottom left) version, additionally those same versions with a cast shadow on the right side. I personally would opt for one of the first two versions, may it be with a shadow or not. (Note, when you've decided I will update my PR and re-add the eyes in the icon's cave which I accidentally removed here.)

**Comment by AntumDeluge** [comment]
I like the contrast flat without shadow.

**Comment by rubenwardy** [comment]
I agree the contrast flat (middle-left) is the best

**Pull request closed without merging**
